"""Rebuild the checked-in offline fonts. Requires fonttools[woff] and brotli.
Sources are SIL OFL fonts from Google Fonts; renamed after subsetting.
Run with: .build-tools/font-env/bin/python scripts/desktop-fonts.py
"""
from pathlib import Path
import hashlib
import json
import unicodedata
import urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / '.build-tools/font-sources'
OUT = ROOT / 'public/fonts'
SPECS = [
    ('notoserifkr', 'NotoSerifKR[wght].ttf', 'Higanbana Serif KR', 'serif-kr', '400 600'),
    ('notoserifjp', 'NotoSerifJP[wght].ttf', 'Higanbana Serif JP', 'serif-jp', '400 600'),
    ('nanumpenscript', 'NanumPenScript-Regular.ttf', 'Higanbana Hand KR', 'hand-kr', '400'),
    ('yomogi', 'Yomogi-Regular.ttf', 'Higanbana Hand JP', 'hand-jp', '400'),
]
CACHE.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)
files = [p for p in (ROOT / 'src').rglob('*') if p.suffix in ('.ts', '.css', '.html')]
files += [ROOT / 'index.html', ROOT / 'higanbana_full_storyboard_revised.md']
text = ''.join(p.read_text() for p in files)
chars = sorted(set(unicodedata.normalize('NFC', text)) | {chr(i) for i in range(32, 127)})
css, manifest = [], {'corpus': ''.join(chars), 'fonts': []}
for directory, filename, family, stem, weights in SPECS:
    base = f'https://raw.githubusercontent.com/google/fonts/main/ofl/{directory}/'
    src = CACHE / filename
    if not src.exists(): urllib.request.urlretrieve(base + urllib.parse.quote(filename), src)
    license_path = OUT / f'{stem}-OFL.txt'
    urllib.request.urlretrieve(base + 'OFL.txt', license_path)
    print(f'Subsetting {family}…', flush=True)
    font = TTFont(src, recalcTimestamp=False)
    options = subset.Options()
    options.flavor = 'woff2'
    options.layout_features = ['*']
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    options.recalc_timestamp = False
    worker = subset.Subsetter(options=options)
    worker.populate(text=''.join(chars))
    worker.subset(font)
    # Respect reserved font names: this is a game-specific derivative.
    for record in font['name'].names:
        if record.nameID in (1, 3, 4, 6, 16):
            value = family.replace(' ', '') if record.nameID == 6 else family
            record.string = value.encode(record.getEncoding())
    font.flavor = 'woff2'
    dest = OUT / f'{stem}.woff2'
    font.save(dest)
    coverage = sorted(font.getBestCmap())
    manifest['fonts'].append({'file': dest.name, 'family': family, 'weights': weights,
        'source': base + filename, 'sourceSha256': hashlib.sha256(src.read_bytes()).hexdigest(),
        'sourceBytes': src.stat().st_size, 'bytes': dest.stat().st_size, 'codepoints': coverage,
        'sha256': hashlib.sha256(dest.read_bytes()).hexdigest()})
    css.append(f'@font-face {{ font-family: "{family}"; font-style: normal; font-weight: {weights}; font-display: swap; src: url("/fonts/{dest.name}") format("woff2"); }}')
    print(f'{family}: {src.stat().st_size:,} → {dest.stat().st_size:,} bytes', flush=True)
(OUT / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
(ROOT / 'src/fonts.css').write_text('/* Generated by scripts/desktop-fonts.py; source licenses in public/fonts. */\n' + '\n'.join(css) + '\n')
