import {loadLegacyStoryAssets} from './legacyStoryAssets';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import * as THREE from 'three';
import type {SurveyPoint} from './survey';
interface Site {id:string;name:string;position:SurveyPoint;radius:number;acts:string;access?:{path:SurveyPoint[];entrancePoint:SurveyPoint}}
interface Route {from:string;to:string;points:SurveyPoint[];needsSlopeWork:boolean;lengthMeters:number}
interface Layout {sites:Site[];routes:Route[]}
/** Review-only volumes and paths. Never enters the walk-collider tree. */
export async function installStoryLayoutReview(scene:THREE.Scene,height:(x:number,z:number)=>number,focus:(position:number[],target:number[])=>void,invalidate:()=>void){
 const response=await fetch('/data/ogimachi/story-layout.json');if(!response.ok)throw Error('스토리 배치 자료를 불러오지 못했습니다.');const layout=await response.json() as Layout;
 scene.fog=null;
 const root=new THREE.Group();root.name='story-layout-review-only';scene.add(root);
 let shrineModel:THREE.Group|null=null;
 const shrine=layout.sites.find(s=>s.id==='shrine');if(shrine){const gltf=await new GLTFLoader().loadAsync('/models/ogimachi/story-shrine.glb');gltf.scene.name='Blender-story-shrine-interior-v4';gltf.scene.position.set(shrine.position[0],height(...shrine.position),shrine.position[1]);gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(gltf.scene);shrineModel=gltf.scene;const interiorLight=new THREE.PointLight(0xffdfb2,18,12,2);interiorLight.position.set(shrine.position[0],height(...shrine.position)+4,shrine.position[1]-7);scene.add(interiorLight);}
 const legacy=await loadLegacyStoryAssets(scene,height);
 const mat=(color:number)=>new THREE.LineBasicMaterial({color,transparent:true,opacity:.95,depthTest:false,fog:false});const gold=mat(0xffd06a),cyan=mat(0x63eeec),orange=mat(0xff744a);
 const line=(points:SurveyPoint[],material:THREE.LineBasicMaterial,lift=2)=>{if(points.length<2)return;const samples:THREE.Vector3[]=[];for(let i=1;i<points.length;i++){const a=points[i-1]!,b=points[i]!,n=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/3));for(let j=i===1?0:1;j<=n;j++){const t=j/n,x=a[0]+(b[0]-a[0])*t,z=a[1]+(b[1]-a[1])*t;samples.push(new THREE.Vector3(x,height(x,z)+lift,z));}}const object=new THREE.Line(new THREE.BufferGeometry().setFromPoints(samples),material);object.renderOrder=100;root.add(object);};
 for(const route of layout.routes)line(route.points,route.needsSlopeWork?orange:gold);
 const dimensions:Record<string,number[]>={shrine:[20,10,16],school:[45,10,30],manor:[24,10,18],hokora:[6,6,6],well:[4,3,4],inn:[18,9,16],grandma:[14,7,18],square:[22,1,22],cemetery:[28,2,25],paddy:[38,1,35],escape:[14,2,12]};
 const unit=new THREE.EdgesGeometry(new THREE.BoxGeometry(1,1,1));
 for(const site of layout.sites){const [x,z]=site.position,y=height(x,z);const circle:SurveyPoint[]=Array.from({length:65},(_,i)=>[x+site.radius*Math.cos(i*Math.PI/32),z+site.radius*Math.sin(i*Math.PI/32)]);line(circle,gold,.8);if(site.access)line(site.access.path,cyan,2.7);
  const dims=dimensions[site.id];if(dims&&site.id!=='shrine'&&site.id!=='well'&&site.id!=='hokora'&&site.id!=='school'){const box=new THREE.LineSegments(unit,gold);box.position.set(x,y+dims[1]!/2,z);box.scale.set(dims[0]!,dims[1]!,dims[2]!);box.renderOrder=100;root.add(box);}
  const canvas=document.createElement('canvas');canvas.width=512;canvas.height=112;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#14242ee8';ctx.fillRect(0,0,512,112);ctx.textAlign='center';ctx.fillStyle='#fff0b8';ctx.font='bold 29px sans-serif';ctx.fillText(site.name,256,44);ctx.fillStyle='#c1d5df';ctx.font='21px sans-serif';ctx.fillText(`ACT ${site.acts} · ${site.id==='shrine'?'Blender 내부 4차':site.id==='well'?'기존 맵 원본 에셋':['school','hokora'].includes(site.id)?'기존 맵 원본 에셋':'공간 검토용'}`,256,82);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false,transparent:true,fog:false}));sprite.position.set(x,y+22,z);sprite.scale.set(45,10,1);sprite.renderOrder=101;root.add(sprite);
 }
 const panel=document.createElement('div');Object.assign(panel.style,{position:'fixed',bottom:'20px',left:'20px',zIndex:'110',background:'#13232eee',color:'#fff',padding:'14px',border:'1px solid #708891',borderRadius:'8px',maxWidth:'min(540px, 90vw)',font:'14px system-ui'});
 const title=document.createElement('strong');title.textContent='기존 사당·학교 및 내부 소품 이식';const detail=document.createElement('p');detail.textContent=`배치 확인 화면 · 학교 소품 ${legacy.school.detail.resident?'원본 모델 로드 완료':'기본 모델 표시 — 상세 모델 로드 실패'} · 플레이 연결 예정`;const select=document.createElement('select');const placeholder=document.createElement('option');placeholder.textContent='가까이 볼 장소';placeholder.value='';select.append(placeholder);for(const site of layout.sites){const option=document.createElement('option');option.value=site.id;option.textContent=site.name;select.append(option);}select.onchange=()=>{const site=layout.sites.find(s=>s.id===select.value);if(!site)return;const [x,z]=site.position,y=height(x,z);if(site.id==='shrine')focus([x+30,y+22,z+40],[x,y+3,z]);else if(site.id==='well')focus([x+6,y+4.5,z+8],[x,y+1.5,z]);else focus([x+65,y+60,z+80],[x,y+3,z]);};
 const overview=document.createElement('button');overview.textContent='전체 배치';overview.onclick=()=>focus([-210,1250,600],[-210,0,-80]);const toggle=document.createElement('button');toggle.textContent='검토 표시 숨기기';toggle.onclick=()=>{root.visible=!root.visible;toggle.textContent=root.visible?'검토 표시 숨기기':'검토 표시 보기';invalidate();};const doorButton=document.createElement('button');doorButton.textContent='신사 문 열기';let doorsOpen=false;const left=shrineModel?.getObjectByName('ShrineDoorLeft'),right=shrineModel?.getObjectByName('ShrineDoorRight');const leftX=left?.position.x??0,rightX=right?.position.x??0;doorButton.disabled=!left||!right;
 const openDoors=(open:boolean)=>{if(!left||!right)return;doorsOpen=open;left.position.x=leftX-(open?2.15:0);right.position.x=rightX+(open?2.15:0);doorButton.textContent=open?'신사 문 닫기':'신사 문 열기';invalidate();};doorButton.onclick=()=>openDoors(!doorsOpen);
 const inside=document.createElement('button');inside.textContent='신사 내부 보기';inside.disabled=!shrineModel;inside.onclick=()=>{if(!shrine)return;openDoors(true);const [x,z]=shrine.position,y=height(x,z);root.visible=false;toggle.textContent='검토 표시 보기';focus([x+1.2,y+2.9,z-4.6],[x,y+2.65,z-9]);};
 const playWell=document.createElement('button');playWell.textContent='우물에서 직접 플레이';playWell.onclick=()=>{location.href='/ogimachi.html?view=detail&play=1&well=1';};const schoolInside=document.createElement('button');schoolInside.textContent='기존 학교 내부';schoolInside.onclick=()=>{const p=legacy.school.broadcastPos;root.visible=false;toggle.textContent='검토 표시 보기';focus([p.x+1.5,p.y+1.7,p.z-3],[p.x,p.y+.8,p.z]);};const hokoraInside=document.createElement('button');hokoraInside.textContent='기존 사당 내부';hokoraInside.onclick=()=>{const p=legacy.hokora.suzuPos;root.visible=false;toggle.textContent='검토 표시 보기';focus([p.x+4,p.y+1.5,p.z+2],[p.x,p.y,p.z]);};panel.append(title,detail,select,overview,toggle,doorButton,inside,playWell,schoolInside,hokoraInside);document.body.append(panel);overview.click();const requested=new URLSearchParams(location.search).get('site');if(requested){select.value=requested;select.dispatchEvent(new Event('change'));}if(new URLSearchParams(location.search).get('inside')==='1'){if(requested==='school')schoolInside.click();else if(requested==='hokora')hokoraInside.click();else inside.click();}if(new URLSearchParams(location.search).get('clean')==='1'){root.visible=false;toggle.textContent='검토 표시 보기';}invalidate();
 return root;
}
